### PR TITLE
Added RatingByGender Test 3 and rehash test 4

### PR DESCRIPTION
**Pull request by Angelawork**
Check for invalid keyword strings in RatingByGender and if rehash handled keys with same hash values.

### CODE REVIEW

**Comment by santoshlite** [comment]
Thanks!

**Comment by G1ngerAle** [comment]
Just to clarify should we return null if we cannot find the keyword in the dataset for all classes?

**Comment by santoshlite** [comment]
I believe yeah

**Comment by Angelawork** [comment]
> Just to clarify should we return null if we cannot find the keyword in the dataset for all classes?

I believed so? as TAs didn't really deny my answer in ED post #1741, then I just decided to put all the edge cases here for testing.

**Comment by G1ngerAle** [comment]
We could add some tests for other classes for null testing as well.

**Comment by G1ngerAle** [comment]
It's done rn. You could check it out in the newest commit.

**Pull request merged**
